### ISSUE TITLE
Incompatibility on Ubuntu 14.10

### ISSUE THREAD

**Issue by florian-asche** [fgrehm/vagrant-lxc#367]
Hi,

i try to bring up a box on Ubuntu 14.10 Host System. It failed badly with this error:
```
USERNAME@apollo:~/chef-repo/chef-cookbook-demo-cdn$ kitchen verify ubuntu-1404
-----> Starting Kitchen (v1.3.1)
-----> Creating <default-ubuntu-1404>...
       Bringing machine 'default' up with 'lxc' provider...
       ==> default: Importing base box 'fgrehm/trusty64-lxc'...
       There was an error executing ["sudo", "/usr/local/bin/vagrant-lxc-wrapper", "lxc-create", "-B", "best", "--template", "vagrant-tmp-default-ubuntu-1404_default_1429795300348_99675", "--name", "default-ubuntu-1404_default_1429795300348_99675", "--", "--tarball", "/home/USERNAME/.vagrant.d/boxes/fgrehm-VAGRANTSLASH-trusty64-lxc/1.2.0/lxc/rootfs.tar.gz", "--config", "/home/USERNAME/.vagrant.d/boxes/fgrehm-VAGRANTSLASH-trusty64-lxc/1.2.0/lxc/lxc-config"]
       
       For more information on the failure, enable detailed logging by setting
       the environment variable VAGRANT_LOG to DEBUG.
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider=lxc ----
STDOUT: Bringing machine 'default' up with 'lxc' provider...
==> default: Importing base box 'fgrehm/trusty64-lxc'...
STDERR: There was an error executing ["sudo", "/usr/local/bin/vagrant-lxc-wrapper", "lxc-create", "-B", "best", "--template", "vagrant-tmp-default-ubuntu-1404_default_1429795300348_99675", "--name", "default-ubuntu-1404_default_1429795300348_99675", "--", "--tarball", "/home/USERNAME/.vagrant.d/boxes/fgrehm-VAGRANTSLASH-trusty64-lxc/1.2.0/lxc/rootfs.tar.gz", "--config", "/home/USERNAME/.vagrant.d/boxes/fgrehm-VAGRANTSLASH-trusty64-lxc/1.2.0/lxc/lxc-config"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
---- End output of vagrant up --no-provision --provider=lxc ----
Ran vagrant up --no-provision --provider=lxc returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

.kitchen.yml:
```
---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      box: fgrehm/trusty64-lxc
      provider: lxc
    run_list:
      - recipe[apt]
  - name: ubuntu-12.04
    driver:
      box: fgrehm/precise64-lxc
      provider: lxc
    run_list:
      - recipe[apt]
  - name: centos-6.4
    driver:
      box: fgrehm/centos6-64-lxc
      provider: lxc
    run_list:
      - recipe[yum]

suites:
  - name: default
    run_list:
      - recipe[monitor::master]
      - recipe[monitor::linux]
      - recipe[demo-cdn::default]
    attributes:
      asy-base:
        ssh_user: vagrant
        replace_keys: false
      uchiwa:
        settings:
            user: ''
            pass: ''
```

Version:
```
USERNAME@apollo:~$ vagrant --version
Vagrant 1.7.2
USERNAME@apollo:~$ vagrant plugin list
vagrant-lxc (1.1.0)
vagrant-share (1.1.3, system)
USERNAME@apollo:~$ lxctl --version
Version: 0.3.0
USERNAME@apollo:~$ lxc-ls --version
1.1.0.alpha2
USERNAME@apollo:~$
```
